<?php

namespace DoctrineORMModule\Proxy\__CG__\Events\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Venue extends \Events\Entity\Venue implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;
    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;
    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }


    /**
     *
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array(
                '__isInitialized__',
                'name',
                'rooms',
                'id',
                'sys_deleted',
                'sys_author',
                'sys_modified',
                'sys_creator',
                'sys_created',
                'street_address_1',
                'street_address_2',
                'co',
                'postbox',
                'postal_code',
                'locality',
                'region',
                'country',
                'latitude',
                'longitude',
                'hashtag',
                'description',
                'abstract',
                'image'
            );
        }

        return array(
            '__isInitialized__',
            'name',
            'rooms',
            'id',
            'sys_deleted',
            'sys_author',
            'sys_modified',
            'sys_creator',
            'sys_created',
            'street_address_1',
            'street_address_2',
            'co',
            'postbox',
            'postal_code',
            'locality',
            'region',
            'country',
            'latitude',
            'longitude',
            'hashtag',
            'description',
            'abstract',
            'image'
        );
    }

    /**
     *
     */
    public function __wakeup()
    {
        if (!$this->__isInitialized__) {
            $this->__initializer__ = function (Venue $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (!array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    /**
     *
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getRooms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRooms', array());

        return parent::getRooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setRooms($rooms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRooms', array($rooms));

        return parent::setRooms($rooms);
    }

    /**
     * {@inheritDoc}
     */
    public function onAfterCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onAfterCreate', array());

        return parent::onAfterCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function onBeforeUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onBeforeUpdate', array());

        return parent::onBeforeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getSys_deleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSys_deleted', array());

        return parent::getSys_deleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setSys_deleted($sys_deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSys_deleted', array($sys_deleted));

        return parent::setSys_deleted($sys_deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getSys_author()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSys_author', array());

        return parent::getSys_author();
    }

    /**
     * {@inheritDoc}
     */
    public function setSys_author($sys_author)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSys_author', array($sys_author));

        return parent::setSys_author($sys_author);
    }

    /**
     * {@inheritDoc}
     */
    public function getSys_modified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSys_modified', array());

        return parent::getSys_modified();
    }

    /**
     * {@inheritDoc}
     */
    public function setSys_modified($sys_modified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSys_modified', array($sys_modified));

        return parent::setSys_modified($sys_modified);
    }

    /**
     * {@inheritDoc}
     */
    public function getSys_creator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSys_creator', array());

        return parent::getSys_creator();
    }

    /**
     * {@inheritDoc}
     */
    public function setSys_creator($sys_creator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSys_creator', array($sys_creator));

        return parent::setSys_creator($sys_creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getSys_created()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSys_created', array());

        return parent::getSys_created();
    }

    /**
     * {@inheritDoc}
     */
    public function setSys_created($sys_created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSys_created', array($sys_created));

        return parent::setSys_created($sys_created);
    }

    /**
     * {@inheritDoc}
     */
    public function onBeforeCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onBeforeCreate', array());

        return parent::onBeforeCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function onAfterUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onAfterUpdate', array());

        return parent::onAfterUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet_address_1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet_address_1', array());

        return parent::getStreet_address_1();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet_address_1($street_address_1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet_address_1',
            array($street_address_1));

        return parent::setStreet_address_1($street_address_1);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet_address_2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet_address_2', array());

        return parent::getStreet_address_2();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet_address_2($street_address_2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet_address_2',
            array($street_address_2));

        return parent::setStreet_address_2($street_address_2);
    }

    /**
     * {@inheritDoc}
     */
    public function getCo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCo', array());

        return parent::getCo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCo($co)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCo', array($co));

        return parent::setCo($co);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostbox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostbox', array());

        return parent::getPostbox();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostbox($postbox)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostbox', array($postbox));

        return parent::setPostbox($postbox);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostal_code()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostal_code', array());

        return parent::getPostal_code();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostal_code($postal_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostal_code', array($postal_code));

        return parent::setPostal_code($postal_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocality', array());

        return parent::getLocality();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocality($locality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocality', array($locality));

        return parent::setLocality($locality);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', array());

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion($region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', array($region));

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', array());

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', array($latitude));

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', array());

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', array($longitude));

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getHashtag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHashtag', array());

        return parent::getHashtag();
    }

    /**
     * {@inheritDoc}
     */
    public function setHashtag($hashtag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHashtag', array($hashtag));

        return parent::setHashtag($hashtag);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbstract()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbstract', array());

        return parent::getAbstract();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbstract($abstract)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbstract', array($abstract));

        return parent::setAbstract($abstract);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function deleteImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deleteImage', array());

        return parent::deleteImage();
    }

}
