<?php

/**
 * aevintyri
 *
 * @category    Apparat
 * @package     Apparat_<Package>
 * @author      Joschi Kuphal <joschi@kuphal.net> / @jkphl
 * @copyright   Copyright © 2015 Joschi Kuphal <joschi@kuphal.net> / @jkphl
 * @license     http://opensource.org/licenses/MIT	The MIT License (MIT)
 */

/***********************************************************************************
 *  The MIT License (MIT)
 *
 *  Copyright © 2015 Joschi Kuphal <joschi@kuphal.net> / @jkphl
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  this software and associated documentation files (the "Software"]); to deal in
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so,
 *  subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 *  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 *  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 *  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 *  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 ***********************************************************************************/

use App\Models\Organizer;
use Illuminate\Database\Seeder;

class OrganizerTableSeeder extends Seeder
{
    public function run()
    {
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'tollwerk GmbH',
            'company'          => '',
            'street_address_1' => 'kommunikation . grafik . design',
            'street_address_2' => 'Lindenaststraße 15',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '90409',
            'locality'         => 'Nürnberg',
            'region'           => 'Bayern',
            'latitude'         => '49.459395',
            'longitude'        => '11.087328',
            'email'            => 'info@tollwerk.de',
            'phone'            => '+49 911 959394-5',
            'fax'              => '+49 911 959394-7',
            'cell'             => '',
            'web'              => 'http://tollwerk.de',
            'facebook'         => 'facebook.com/tollwerk',
            'twitter'          => 'tollwerk',
            'xing'             => 'www.xing.com/companies/tollwerk%2525c2%2525aegmbh',
            'gplus'            => 'plus.google.com/b/103389319737184133956/+TollwerkDe',
            'image'            => '/img/organizer/organizer-1.png'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Markus Teschner',
            'company'          => '',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => 'Nürnberg',
            'region'           => 'Bayern',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'mteschner.nue@googlemail.com',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => '',
            'facebook'         => '',
            'twitter'          => 'markusteschner',
            'xing'             => 'www.xing.com/profile/Markus_Teschner',
            'gplus'            => 'plus.google.com/+MarkusTeschner',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Tim Schikora',
            'company'          => 'Insight Innovation GmbH',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => 'Nürnberg',
            'region'           => 'Bayern',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'tim@insight-innovation.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.insight-innovation.de/',
            'facebook'         => 'www.facebook.com/InsightInnovation',
            'twitter'          => 'InsightInno',
            'xing'             => '',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-3.png'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Stefan Wendhausen',
            'company'          => '',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => 'Nürnberg',
            'region'           => 'Bayern',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'stefan.wendhausen@tec-promotion.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.tec-promotion.de/',
            'facebook'         => '',
            'twitter'          => 'inwend',
            'xing'             => 'www.xing.com/profile/Stefan_Wendhausen',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-4.jpg'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Christiane Germann',
            'company'          => '',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => 'Nürnberg',
            'region'           => 'Bayern',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'christiane.germann@icloud.com',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.germann-socialmedia.com/',
            'facebook'         => 'www.facebook.com/christiane.germann',
            'twitter'          => 'Miss_McBeal',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'insertEFFECT',
            'company'          => '',
            'street_address_1' => 'insertEFFECT GmbH',
            'street_address_2' => 'Hessestr. 5-7',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '90443',
            'locality'         => 'Nürnberg',
            'region'           => 'Bayern',
            'latitude'         => '49.445269',
            'longitude'        => '11.058533',
            'email'            => 'info@inserteffect.com',
            'phone'            => '0911/274487-0',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'https://www.inserteffect.com/',
            'facebook'         => 'www.facebook.com/inserteffect',
            'twitter'          => 'inserteffect',
            'xing'             => 'www.xing.com/companies/inserteffectgmbh',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-6.png'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Michael Leibrecht',
            'company'          => 'machen.de Medien und Marketing GmbH ',
            'street_address_1' => 'Benno-Strauß-Straße 7',
            'street_address_2' => 'Eingang A',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '90763',
            'locality'         => 'Fürth',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'm.leibrecht@machen.de',
            'phone'            => '0911 93 777 93',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.machen.de/',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => 'www.xing.com/companies/machen.demedienundmarketinggmbh?keyword=machen.de%20medien%20und%20marketing%20gmbh',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Stefan Kremer',
            'company'          => '',
            'street_address_1' => 'An der Thalach 2',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '91177',
            'locality'         => 'Thalmässing',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'stefan@redaktiv.de',
            'phone'            => '09173 – 7939884',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://stefankremer.de/',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-8.jpg'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Dirk Murschall',
            'company'          => '',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => 'Nürnberg',
            'region'           => 'Bayern',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'mail@dirkmurschall.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '+49 176 5411 6672',
            'web'              => 'https://www.dirkmurschall.de/',
            'facebook'         => 'www.facebook.com/mursonic',
            'twitter'          => 'srbanister',
            'xing'             => 'www.xing.com/profile/Dirk_Murschall',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-9.jpg'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Martin Heider',
            'company'          => '',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => 'Nürnberg',
            'region'           => 'Bayern',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'kontakt@infomar.de',
            'phone'            => '+49 911 97791450',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.infomar.de/',
            'facebook'         => '',
            'twitter'          => 'martinheider',
            'xing'             => '',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-10.jpg'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Christian Lamprecht',
            'company'          => 'Shoptimax',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => 'Nürnberg',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => '',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.shoptimax.de/',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => 'www.xing.com/companies/shoptimaxgmbh',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-11.png'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Stefan Probst',
            'company'          => 'Open Source Business Foundation',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => '',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.osbf.eu/de/',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Ralph Haydl',
            'company'          => 'Pilzpaket',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'info@pilzpaket.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '0176 56590453',
            'web'              => 'http://www.pilzpaket.de/',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-13.png'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Marco Emrich',
            'company'          => 'Softwerkskammer Nürnberg',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'm.emrich@webmasters.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'https://www.softwerkskammer.org',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Arthur Soballa',
            'company'          => 'Werbebotschaft',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'asoballa@werbebotschaft.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.werbebotschaft.de',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-15.jpeg'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Lucian Katzbach',
            'company'          => 'LUKA Venture GmbH',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'lk@lukaventure.de',
            'phone'            => '+49 (0) 911 – 14 87 97 03 – 0',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.lukaventure.de',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Kristian Knobloch',
            'company'          => 'NETZKOLLEKTIV GmbH',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'kristian.knobloch@netzkollektiv.com',
            'phone'            => '01779605850',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.netzkollektiv.com',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Petra Beer',
            'company'          => 'Müller Medien',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'petra.beer@muellerverlag.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => '',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Udo Neßhöver',
            'company'          => '.Net Usergroup Franken',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'udo@dodnedder.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => 'http://www.dodnedder.de/',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Markus Neubauer',
            'company'          => 'Silbury',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'markus.neubauer@silbury.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => '',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Stefan Popp',
            'company'          => 'Anwalt.de',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'popp@anwalt.de',
            'phone'            => '+49 911 815150',
            'fax'              => '',
            'cell'             => '',
            'web'              => '',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => '/img/organizer/organizer-21.png'
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Michael Schottenhammer',
            'company'          => 'Stadt Nürnberg',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'Michael.Schottenhammer@stadt.nuernberg.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => '',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Ulf Schubert',
            'company'          => '',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'ulf.schubert@gmail.com',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => '',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Thomas Seel',
            'company'          => 'dns - digital nervous systems GmbH',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => '',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => '',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
        Organizer::create([
            'usergroup_id'     => '1',
            'country_id'       => '276',
            'name'             => 'Benjamin Bauer',
            'company'          => '',
            'street_address_1' => '',
            'street_address_2' => '',
            'co'               => '',
            'postbox'          => '',
            'postal_code'      => '',
            'locality'         => '',
            'region'           => '',
            'latitude'         => '0',
            'longitude'        => '0',
            'email'            => 'benjamin.bauer@fau.de',
            'phone'            => '',
            'fax'              => '',
            'cell'             => '',
            'web'              => '',
            'facebook'         => '',
            'twitter'          => '',
            'xing'             => '',
            'gplus'            => '',
            'image'            => ''
        ]);
    }
}
