<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
        <meta charset="utf-8"><?php

        echo $this->headTitle($this->translate('application'))->setSeparator(' - ')->setAutoEscape(false);

        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
                  ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink(array('rel'  => 'shortcut icon',
                                   'type' => 'image/vnd.microsoft.icon',
                                   'href' => $this->basePath().'/img/favicon.ico'
        ))
//                         ->prependStylesheet($this->basePath() . '/css/style.css')
//                         ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
//                         ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');

                  ->appendStylesheet('http://fonts.googleapis.com/css?family=Droid+Sans')
                  ->appendStylesheet($this->basePath().'/css/events.min.css');

        echo $this->headScript()->prependFile($this->basePath().'/js/vendor/modernizr.js');
        // 			            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        // 			            ->prependFile($this->basePath() . '/js/jquery.min.js')
        // 			            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        // 			            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?></head>
    <body>
        <nav class="top-bar" data-topbar="true" role="navigation">
            <ul class="title-area">
                <li class="name">
                    <h1>
                        <a href="<?php echo $this->url('event') ?>"><?php echo $this->translate('events.section.label.event.calendar') ?></a>
                    </h1>
                </li>
                <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            </ul>

            <section class="top-bar-section">
                <?php
                echo $this->navigation('navright')->menu()->setUlClass('right')->setMinDepth(0)->setMaxDepth(1)
                          ->render();
                echo $this->navigation('navleft')->menu()->setUlClass('left')->setMinDepth(0)->setMaxDepth(1)->render();
                ?>
            </section>
        </nav>


        <main role="main" class="container">
            <article><?php echo $this->content; ?></article>
            <footer>
                <p>&copy; <?php echo date('Y').' '.$this->translate('footer.legal'); ?></p>
            </footer>
        </main><?php

        echo $this->inlineScript();

        ?>
        <script src="<?php echo $this->basePath() ?>/js/jQuery.min.js"></script>
        <script src="<?php echo $this->basePath() ?>/js/foundation.min.js"></script>
        <script src="<?php echo $this->basePath() ?>/js/events.min.js"></script>
    </body>
</html>
