<?php


// Header
if ($this->link->getPresenter()) {
    $backlink = $this->url('presenter', array('action' => 'edit', 'id' => $this->link->getPresenter()->getId()),
        array('fragment' => 'associations'));
    $action   = array('presenter' => $this->link->getPresenter()->getId());
} else {
    $backlink = $this->url('presenter', array('action' => 'edit', 'id' => $this->link->getSession()->getId()),
        array('fragment' => 'associations'));
    $action   = array('session' => $this->link->getSession()->getId());
}
echo $this->partial('partials/common/header.phtml', array(
    'header' => $this->translate('events.section.label.link.new'),
    'buttons' => array($backlink => $this->translate('button.back'))
));

// Messages
// 	echo $this->flashMessagesHelper($flashMessages);

$form = $this->form;
$link = $form->get('link');
$form->setAttribute('action',
    $this->url('link', array_merge(array('action' => 'add', 'id' => $this->link->getId()), $action)));
$form->prepare();

echo $this->form()->openTag($form);

?>

    <fieldset id="general">
        <legend><?php echo $this->translate('form.legend.general'); ?></legend>
        <div class="row">
            <div class="large-6 columns">
                <?php echo $this->formRow($link->get('name')); ?>
            </div>
            <div class="large-6 columns">
                <?php echo $this->formRow($link->get('url')); ?>
            </div>
        </div>
    </fieldset>
    <div class="row">
        <div class="large-12 columns">
            <ul class="button-group">
                <li><?php echo $this->formSubmit($form->get('create')); ?></li>
                <li><?php echo $this->formSubmit($form->get('createclose')); ?></li>
            </ul>
        </div>
    </div>

<?php

/** Hidden fields **/
echo $this->formHidden($link->get('id'));
/** END - Hidden fields **/

echo $this->form()->closeTag($form);
?>