<?php

echo $this->partial('auth/layout/nav-menu', array('navMenu' => $this->navMenu, 'user' => $this->identity()));

$form = $this->form;

/**
 *
 * Set form fields classes and placeholders here
 *
 */

$form->setAttributes(array(
    'class' => 'form'
));

$form->get('newPasswordVerify')->setAttributes(array(
    'class' => 'form-control input-lg',
    'placeholder' => $this->translate('auth.label.password.new.confirm')
));

$form->get('submit')->setAttributes(array(
    'class' => 'btn btn btn-success btn-lg', 
    'value' => $this->translate('auth.button.password.change')
));

$form->prepare();
?>
<div class="jumbotron">
  <h2><?php echo $this->translate('auth.header.password.change')?></h2>
    <div class="container" id="wrap">
	  <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <?php echo $this->form()->openTag($form); ?>
            <div class="row">
              <div class="col-sm-12"> 
                <?php echo $this->message ?>      
              </div>
            </div>
            <div class="col-sm-12">
              <strong><?php echo $this->translate('auth.label.question') ?></strong>:
              <br />
              <em><?php echo $this->question ?></em>      
            </div>
            <input type="text" autocomplete="off" value="" placeholder="<?php echo $this->translate('auth.label.answer') ?>" class="form-control input-lg" required="required" name="answer">
            <?php
              $element = $form->get('answer');
              echo $this->formElementErrors($element);
            ?>
            <input type="password" autocomplete="off" value="" placeholder="<?php echo $this->translate('auth.label.password.new') ?>" class="form-control input-lg" required="required" name="password">
            <?php
              $element = $form->get('password');
              echo $this->formElementErrors($element);
            ?>
            <?php
              $element = $form->get('newPasswordVerify');
              echo $this->formElement($element);
              echo $this->formElementErrors($element);
            ?>
            <div class="row">
              <div class="col-sm-12"> 
                <?php echo $this->formRow($form->get('submit'))?>              
              </div>
            </div>
            <?php 
              echo $this->formRow($form->get('csrf'));
              echo $this->form()->closeTag();
            ?>         
        </div>
      </div>            
    </div>
</div>
