<?php

echo $this->partial('auth/layout/nav-menu', array(
	'navMenu' => $this->navMenu,
	'user' => $this->identity()
));

$form = $this->form;

/**
 * Set form fields classes and placeholders here
 */

$form->setAttributes(array(
	'class' => 'form'
));

$form->get('name')->setAttributes(array(
	'required' => 'false',
	'class' => 'form-control input-lg',
	'placeholder' => $this->translate('auth.label.name')
));

$form->get('submit')->setAttributes(array(
	'class' => 'btn btn btn-success btn-lg',
	'value' => $this->translate('auth.button.profile.update')
));

$form->prepare();
?>
<div class="jumbotron">
	<h2><?php echo $this->translate('auth.header.profile.edit')?></h2>
	<div class="container" id="wrap">
		<div class="row">
			<div class="col-md-8 col-md-offset-3">
				<?php echo $this->form()->openTag($form); ?>
					<div class="row">
						<div class="col-sm-12"><?php echo $this->message ?></div>
					</div>
					<div><span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('auth.label.username') ?>: </span><?php echo $this->username?></div>
					<div><span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('auth.label.password') ?>: </span>******<br /> <a href="<?php echo $this->url('user-register', array('action' => 'change-password'));?>"><?php echo $this->translate('auth.label.password.change'); ?></a></div>
					<div><span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('auth.label.email') ?>: </span><?php echo $this->email?><br/ > <a href="<?php echo $this->url('user-register', array('action' => 'change-email'));?>"><?php echo $this->translate('auth.label.email.change'); ?></a></div>
					<div><span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('auth.label.question') ?>: </span><?php echo $this->securityQuestion?><br/ ><a href="<?php echo $this->url('user-register', array('action' => 'change-security-question'));?>"><?php echo $this->translate('auth.label.question.change'); ?></a></div>
					<div><span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('auth.label.name') ?>:</span><br/ ><?php
						$element = $form->get('name');
						echo $this->formElement($element);
						echo $this->formElementErrors($element);
					?></div>
					<div class="row"><div class="col-sm-12"><?php echo $this->formRow($form->get('submit'))?></div>
				</div><?php
					echo $this->formRow($form->get('csrf'));
					echo $this->form()->closeTag();
			?></div>
		</div>
	</div>
</div>
