<?php

/**
 * Event management
 *
 * @category       Tollwerk
 * @package        Tollwerk_Events
 * @author         Joschi Kuphal <joschi@kuphal.net>
 * @copyright      Copyright © 2014 tollwerk GmbH <info@tollwerk.de>
 * @license        http://opensource.org/licenses/BSD-3-Clause	The BSD 3-Clause License
 */
echo $this->partial('auth/layout/nav-menu', array('navMenu' => $this->navMenu, 'user' => $this->identity()));

$form = $this->form;

/**
 *
 * Set form fields classes and placeholders here
 *
 */

$form->setAttributes(array(
    'class' => 'form'
));

$form->get('username')->setAttributes(array(
    'class'       => 'form-control input-lg',
    'placeholder' => $this->translate('auth.label.username')
));

$form->get('name')->setAttributes(array(
    'required'    => 'false',
    'class'       => 'form-control input-lg',
    'placeholder' => $this->translate('auth.label.name')
));

$form->get('email')->setAttributes(array(
    'class'       => 'form-control input-lg',
    'placeholder' => $this->translate('auth.label.email')
));

$form->get('password')->setAttributes(array(
    'class'       => 'form-control input-lg',
    'placeholder' => $this->translate('auth.label.password')
));

$form->get('passwordVerify')->setAttributes(array(
    'class'       => 'form-control input-lg',
    'placeholder' => $this->translate('auth.label.password.confirm')
));

$form->get('question')->setAttributes(array(
    'class' => 'form-control input-lg',
));

$form->get('usergroup')->setAttributes(array(
    'class' => 'form-control input-lg',
));

$form->get('answer')->setAttributes(array(
    'class'       => 'form-control input-lg',
    'placeholder' => $this->translate('auth.label.answer')
));

$form->get('captcha')->setAttributes(array(
    'required'    => 'true',
    'class'       => 'form-control input-lg',
    'placeholder' => $this->translate('auth.label.captcha')
));

$form->get('submit')->setAttributes(array(
    'class' => 'btn btn btn-success btn-lg',
    'value' => $this->translate('auth.button.signup')
));

$form->get('login')->setAttributes(array(
    'class' => 'btn btn btn-warning btn-lg',
    'label' => $this->translate('auth.button.signin')
));

$form->prepare();
?>
<div class="jumbotron">
    <h2><?php echo $this->translate('auth.header.signup') ?></h2>
    <div class="container" id="wrap">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <?php echo $this->form()->openTag($form); ?>
                <?php
                $element = $form->get('username');
                echo $this->formElement($element);
                echo $this->formElementErrors($element);
                ?>
                <div class="row">
                    <div class="col-xs-12 col-md-12">
                        <?php
                        $element = $form->get('name');
                        echo $this->formElement($element);
                        echo $this->formElementErrors($element);
                        ?>
                    </div>
                </div>
                <?php
                $element = $form->get('email');
                echo $this->formElement($element);
                echo $this->formElementErrors($element);
                ?>
                <div class="row">
                    <div class="col-xs-6 col-md-6">
                        <?php
                        $element = $form->get('password');
                        echo $this->formPassword($element);
                        echo $this->formElementErrors($element);
                        ?>
                    </div>
                    <div class="col-xs-6 col-md-6">
                        <?php
                        $element = $form->get('passwordVerify');
                        echo $this->formPassword($element);
                        echo $this->formElementErrors($element);
                        ?>
                    </div>
                </div>
                <?php
                $element = $form->get('question');
                echo $this->formElement($element);
                echo $this->formElementErrors($element);

                $element = $form->get('answer');
                echo $this->formElement($element);
                echo $this->formElementErrors($element);

                $element = $form->get('usergroup');
                echo $this->formElement($element);
                echo $this->formElementErrors($element);
                ?>
                <div class="row">
                    <div class="col-xs-12 col-md-12">
                        <?php
                        $element = $form->get('captcha');
                        echo $this->formElement($element);
                        echo $this->formElementErrors($element);
                        ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <?php echo $this->formRow($form->get('submit')) ?>
                        <?php echo $this->formButton($form->get('login')) ?>
                    </div>
                </div>
                <?php
                echo $this->formRow($form->get('csrf'));
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
