<?php

echo $this->partial('partials/common/header.phtml', array('header' => $this->translate('auth.header.signin')));

$form		= $this->form;

$form->setAttributes(array(
    'class' => 'form'
));

$form->get('usernameOrEmail')->setAttributes(array(
    'placeholder' => $this->translate('auth.label.usernameoremail')
));

$form->get('password')->setAttributes(array(
    'placeholder' => $this->translate('auth.label.password')
));

$form->get('rememberme')->setAttributes(array(
    'id' => 'rememberme', 
));

$form->get('captcha')->setAttributes(array(
    'required' => 'true',
    'placeholder' => $this->translate('auth.label.captcha')
));

$form->get('submit')->setAttributes(array(
    'class' => 'button radius', 
    'value' => $this->translate('auth.button.signin')
));

$form->prepare();

echo $this->form()->openTag($form);

?><fieldset id="auth">
	<legend><?php echo $this->translate('form.legend.credentials'); ?></legend>
	<?php
	
		if (strlen($this->messages)):
	
	?><div class="row">
		<div class="large-12 columns">
			<?php echo $this->messages; ?>
		</div>
	</div><?php
	
		endif;
	
	?><div class="row">
		<div class="large-12 columns"><?php
			$element		= $form->get('usernameOrEmail');
			echo $this->formLabel($element, $this->translate('auth.label.username'));
			echo $this->formElement($element);
			echo $this->formElementErrors($element);
		
		?></div>
	</div>
	<div class="row">
		<div class="large-12 columns"><?php
		
			$element		= $form->get('password');
			echo $this->formLabel($element, $this->translate('auth.label.password'));
			echo $this->formElement($element);
			echo $this->formElementErrors($element);
		
		?></div>
	</div>
	<div class="row">
		<div class="large-12 columns"><?php
			$element		= $form->get('captcha');
			echo $this->formLabel($element, $this->translate('auth.label.captcha'));
			echo $this->formElement($element);
			echo $this->formElementErrors($element);
		
		?></div>
	</div>
	<div class="row">
		<div class="large-12 columns"><?php
		
			$element		= $form->get('rememberme');
			 echo $this->formLabel($element, $this->formCheckbox($element), 'append');
			echo $this->formElementErrors($element);
		
		?></div>
	</div>
	<div class="row controls">
		<div class="large-12 columns"><?php
		
			echo $this->formRow($form->get('submit'));
			echo $this->formRow($form->get('csrf'));
		
		?></div>
	</div>
</fieldset><?php
	
	/** Hidden fields **/
// 	echo $this->formHidden($link->get('id'));
	/** END - Hidden fields **/
	
	echo $this->form()->closeTag($form);

	$this->translate('form.legend.credentials');
	$this->translate('auth.section.label.signin');
	$this->translate('auth.section.label.logout');
	$this->translate('auth.section.label.reset');

?>
