<?php

// Header
echo $this->partial('partials/common/header.phtml', array(
    'header' => $this->translate('events.section.label.day.new'),
    'buttons' => array(
        $this->url('event', array('action' => 'edit', 'type' => 'single', 'id' => $this->day->getEvent()->getId()),
            array('fragment' => 'days')) => $this->translate('button.back')
    )
));

// Messages
// 	echo $this->flashMessagesHelper($flashMessages);

$form = $this->form;
$day  = $form->get('day');
$form->setAttribute('action', $this->url('day', array('action' => 'add', 'event' => $this->day->getEvent()->getId())));
$form->prepare();

echo $this->form()->openTag($form);

?>

    <fieldset id="general">
        <legend><?php echo $this->translate('form.legend.general'); ?></legend>
        <div class="row">
            <div class="large-12 columns">
                <?php echo $this->formRow($day->get('date')); ?>
            </div>
        </div>
    </fieldset>
    <div class="row">
        <div class="large-12 columns">
            <ul class="button-group">
                <li><?php echo $this->formSubmit($form->get('create')); ?></li>
                <li><?php echo $this->formSubmit($form->get('createclose')); ?></li>
            </ul>
        </div>
    </div>

<?php

/** Hidden fields **/
echo $this->formHidden($day->get('id'));
echo $this->formHidden($day->get('event'));
/** END - Hidden fields **/

echo $this->form()->closeTag($form);
?>