<?php

/**
 * Event management
 *
 * @category	Tollwerk
 * @package		Tollwerk_Events
 * @author		Joschi Kuphal <joschi@kuphal.net>
 * @copyright	Copyright © 2014 tollwerk GmbH <info@tollwerk.de>
 * @license		http://opensource.org/licenses/BSD-3-Clause	The BSD 3-Clause License
 */
$form = $this->form;

/**
 *
 * Set form fields classes and placeholders here
 *
 */

$form->setAttributes(array(
    'class' => 'form'
));

$form->get('username')->setAttributes(array(
    'required' => 'true',
    'class' => 'form-control input-lg', 
    'placeholder' => $this->translate('auth.label.username')
));

$form->get('name')->setAttributes(array(
    'required' => 'false',
    'class' => 'form-control input-lg', 
    'placeholder' => $this->translate('auth.label.name')
));

$form->get('email')->setAttributes(array(
    'required' => 'true',
    'class' => 'form-control input-lg', 
    'placeholder' => $this->translate('auth.label.email')
));

// $form->get('active')->setAttributes(array(
//     'required' => 'true',
//     'class' => 'form-control input-lg', 
// ));

$form->get('question')->setAttributes(array(
    'required' => 'true',
    'class' => 'form-control input-lg', 
));

$form->get('answer')->setAttributes(array(
    'required' => 'true',
    'class' => 'form-control input-lg', 
    'placeholder' => $this->translate('auth.label.answer')
));

$form->get('usergroup')->setAttributes(array(
	'class' => 'form-control input-lg',
));

$form->get('submit')->setAttributes(array(
    'class' => 'btn btn btn-success btn-lg', 
    'value' => $this->translate('auth.label.edit.user')
));


$form->prepare();
?>
<div class="jumbotron">
  <h2><?php echo $this->translate('auth.header.user.edit')?></h2>
    <div class="container" id="wrap">
	  <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <?php echo $this->form()->openTag($form); ?>
            <?php
              $element = $form->get('username');
              echo $this->formElement($element);
              echo $this->formElementErrors($element);
            ?>
            <?php
                  $element = $form->get('name');
                  echo $this->formElement($element);
                  echo $this->formElementErrors($element);

                  $element = $form->get('email');
	              echo $this->formElement($element);
	              echo $this->formElementErrors($element);
            ?>
            <div class="row">
              <span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('auth.label.password.change'); ?>: </span>******
              <br />
              <a href="<?php echo $this->url('user-register', array('action' => 'change-password'));?>">
                <?php echo $this->translate('auth.label.password.change'); ?>
              </a>
            </div>
            <?php
                  $element = $form->get('question');
                  echo $this->formElement($element);
                  echo $this->formElementErrors($element);
                  
                  $element = $form->get('answer');
                  echo $this->formElement($element);
                  echo $this->formElementErrors($element);
                  
                  $element = $form->get('usergroup');
                  echo $this->formElement($element);
                  echo $this->formElementErrors($element);
                ?>
            <div class="row">
              <div class="col-sm-12"> 
                <?php echo $this->formRow($form->get('submit'))?>              
              </div>
            </div>
          <?php 
            echo $this->formRow($form->get('csrf'));
            echo $this->form()->closeTag();
          ?>         
        </div>
      </div>            
    </div>
</div>
