<?php

	// Header
	echo $this->partial('partials/common/header.phtml', array('header' => $this->translate('events.section.label.tag.new'), 'buttons' => array($this->url('tag', array('action' => 'list')) => $this->translate('button.back'))));
	
	// Messages
// 	echo $this->flashMessagesHelper($flashMessages);
	
	$form 			= $this->form;
	$tag		= $form->get('tag');
	$form->setAttribute('action', $this->url('tag', array('action' => 'add')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	
?>

<fieldset id="general">
	<legend><?php echo $this->translate('form.legend.general'); ?></legend>
	<div class="row">
		<div class="large-6 columns">
			<?php echo $this->formRow($tag->get('name')); ?>
		</div>
		<div class="large-6 columns">
			<?php echo $this->formRow($tag->get('color')); ?>
		</div>
	</div>
</fieldset>
<div class="row">
	<div class="large-12 columns">
		<ul class="button-group">
		  <li><?php echo $this->formSubmit($form->get('create')); ?></li>
		  <li><?php echo $this->formSubmit($form->get('createclose')); ?></li>
		</ul>
	</div>
</div>
	
<?php
	
	/** Hidden fields **/
	echo $this->formHidden($tag->get('id'));
	/** END - Hidden fields **/
	
	echo $this->form()->closeTag($form);
?>