<fieldset id="address">
	<legend><?php echo $this->translate('form.legend.address'); ?></legend>
	<div class="row">
		<div class="large-6 columns">
			<?php echo $this->formRow($subject->get('street_address_1')); ?>
		</div>
		<div class="large-6 columns">
			<?php echo $this->formRow($subject->get('co')); ?>
		</div>
	</div>
	<div class="row">
		<div class="large-6 columns">
			<?php echo $this->formRow($subject->get('street_address_2')); ?>
		</div>
		<div class="large-6 columns">
			<?php echo $this->formRow($subject->get('postbox')); ?>
		</div>
	</div>
	<div class="row">
		<div class="large-3 columns">
			<?php echo $this->formRow($subject->get('postal_code')); ?>
		</div>
		<div class="large-9 columns">
			<?php echo $this->formRow($subject->get('locality')); ?>
		</div>
	</div>
	<div class="row">
		<div class="large-6 columns">
			<?php echo $this->formRow($subject->get('country')); ?>
		</div>
		<div class="large-6 columns">
			<?php echo $this->formRow($subject->get('region')); ?>
		</div>
	</div>
	<div class="row">
		<div class="large-6 columns">
			<?php echo $this->formRow($subject->get('latitude')); ?>
		</div>
		<div class="large-6 columns">
			<?php echo $this->formRow($subject->get('longitude')); ?>
		</div>
	</div>
</fieldset>