<fieldset id="contact">
    <legend><?php echo $this->translate('form.legend.contact'); ?></legend>
    <div class="row">
        <div class="large-4 columns">
            <?php echo $this->formRow($subject->get('phone')); ?>
        </div>
        <div class="large-4 columns">
            <?php echo $this->formRow($subject->get('cell')); ?>
        </div>
        <div class="large-4 columns">
            <?php echo $this->formRow($subject->get('fax')); ?>
        </div>
    </div>
    <div class="row">
        <div class="large-6 columns">
            <?php echo $this->formRow($subject->get('email')); ?>
        </div>
        <div class="large-6 columns">
            <?php echo $this->formRow($subject->get('web')); ?>
        </div>
    </div>
    <div class="row">
        <div class="large-6 columns">
            <div class="row collapse">
                <?php echo $this->formLabel($subject->get('facebook')); ?>
                <div class="small-3 large-2 columns">
                    <span class="prefix text-right">https://</span>
                </div>
                <div class="small-9 large-10 columns">
                    <?php echo $this->formInput($subject->get('facebook')); ?>
                </div>
            </div>
        </div>
        <div class="large-6 columns">
            <div class="row collapse">
                <?php echo $this->formLabel($subject->get('gplus')); ?>
                <div class="small-3 large-2 columns">
                    <span class="prefix text-right">https://</span>
                </div>
                <div class="small-9 large-10 columns">
                    <?php echo $this->formInput($subject->get('gplus')); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="large-6 columns">
            <div class="row collapse">
                <?php echo $this->formLabel($subject->get('xing')); ?>
                <div class="small-3 large-2 columns">
                    <span class="prefix text-right">https://</span>
                </div>
                <div class="small-9 large-10 columns">
                    <?php echo $this->formInput($subject->get('xing')); ?>
                </div>
            </div>
        </div>
        <div class="large-6 columns">
            <div class="row collapse">
                <?php echo $this->formLabel($subject->get('twitter')); ?>
                <div class="small-3 large-2 columns">
                    <span class="prefix text-right">@</span>
                </div>
                <div class="small-9 large-10 columns">
                    <?php echo $this->formInput($subject->get('twitter')); ?>
                </div>
            </div>
        </div>
    </div>
</fieldset>